site_name: "euroleague_api API documentation"
site_url: https://yourdomain.example.com/  # update as needed
repo_url: https://github.com/giasemidis/euroleague_api

# directory containing the documentation source files
docs_dir: "docs/euroleague_api"

nav:
  - Home: index.md
  - EuroLeagueData: EuroLeagueData.md
  - Boxscore Data: boxscore_data.md
  - Game Metadata: game_metadata.md
  - Game Stats: game_stats.md
  - Player Stats: player_stats.md
  - Play-by-Play Data: play_by_play_data.md
  - Shot Data: shot_data.md
  - Standings: standings.md
  - Team Stats: team_stats.md
  - Utils: utils.md

# you can switch themes; "material" requires the mkdocs-material package
theme:
  name: "material"
  navigation_depth: 5
  features:
    - content.actions.edit
    - content.code.view
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
    - toc.follow

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
#  - mkdocstrings  # uncomment if you want autogenerated docs from source
